/*
 * This file is generated by jOOQ.
 */
package io.github.org.programming.jooq.tables.pojos;


import java.io.Serializable;
import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Askthread implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String  memberId;
    private final String  guildId;
    private final Integer amount;
    private final Instant timeStamp;

    public Askthread(Askthread value) {
        this.memberId = value.memberId;
        this.guildId = value.guildId;
        this.amount = value.amount;
        this.timeStamp = value.timeStamp;
    }

    public Askthread(
        String  memberId,
        String  guildId,
        Integer amount,
        Instant timeStamp
    ) {
        this.memberId = memberId;
        this.guildId = guildId;
        this.amount = amount;
        this.timeStamp = timeStamp;
    }

    /**
     * Getter for <code>public.askthread.member_id</code>.
     */
    public String getMemberId() {
        return this.memberId;
    }

    /**
     * Getter for <code>public.askthread.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.askthread.amount</code>.
     */
    public Integer getAmount() {
        return this.amount;
    }

    /**
     * Getter for <code>public.askthread.time_stamp</code>.
     */
    public Instant getTimeStamp() {
        return this.timeStamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Askthread (");

        sb.append(memberId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(amount);
        sb.append(", ").append(timeStamp);

        sb.append(")");
        return sb.toString();
    }
}
