/*
 * This file is generated by jOOQ.
 */
package io.github.org.programming.jooq.tables.pojos;


import java.io.Serializable;
import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Moderation implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String guildId;
    private final String userId;
    private final String moderatorId;
    private final Instant timeStamp;
    private final Integer amountOfWarnings;
    private final String reason;
    private final String type;

    public Moderation(Moderation value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.userId = value.userId;
        this.moderatorId = value.moderatorId;
        this.timeStamp = value.timeStamp;
        this.amountOfWarnings = value.amountOfWarnings;
        this.reason = value.reason;
        this.type = value.type;
    }

    public Moderation(
        Integer id,
        String guildId,
        String userId,
        String moderatorId,
        Instant timeStamp,
        Integer amountOfWarnings,
        String reason,
        String type
    ) {
        this.id = id;
        this.guildId = guildId;
        this.userId = userId;
        this.moderatorId = moderatorId;
        this.timeStamp = timeStamp;
        this.amountOfWarnings = amountOfWarnings;
        this.reason = reason;
        this.type = type;
    }

    /**
     * Getter for <code>public.moderation.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.moderation.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.moderation.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.moderation.moderator_id</code>.
     */
    public String getModeratorId() {
        return this.moderatorId;
    }

    /**
     * Getter for <code>public.moderation.time_stamp</code>.
     */
    public Instant getTimeStamp() {
        return this.timeStamp;
    }

    /**
     * Getter for <code>public.moderation.amount_of_warnings</code>.
     */
    public Integer getAmountOfWarnings() {
        return this.amountOfWarnings;
    }

    /**
     * Getter for <code>public.moderation.reason</code>.
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Getter for <code>public.moderation.type</code>.
     */
    public String getType() {
        return this.type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Moderation (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(userId);
        sb.append(", ").append(moderatorId);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append(amountOfWarnings);
        sb.append(", ").append(reason);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
