/*
 * This file is generated by jOOQ.
 */
package io.github.org.programming.jooq.tables.pojos;


import org.jooq.types.DayToSecond;

import java.io.Serializable;
import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tempban implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer     id;
    private final String      guildId;
    private final String      userId;
    private final String      moderatorId;
    private final DayToSecond duration;
    private final Instant     start;
    private final String      reason;

    public Tempban(Tempban value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.userId = value.userId;
        this.moderatorId = value.moderatorId;
        this.duration = value.duration;
        this.start = value.start;
        this.reason = value.reason;
    }

    public Tempban(
        Integer     id,
        String      guildId,
        String      userId,
        String      moderatorId,
        DayToSecond duration,
        Instant     start,
        String      reason
    ) {
        this.id = id;
        this.guildId = guildId;
        this.userId = userId;
        this.moderatorId = moderatorId;
        this.duration = duration;
        this.start = start;
        this.reason = reason;
    }

    /**
     * Getter for <code>public.tempban.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.tempban.guild_id</code>.
     */
    public String getGuildId() {
        return this.guildId;
    }

    /**
     * Getter for <code>public.tempban.user_id</code>.
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.tempban.moderator_id</code>.
     */
    public String getModeratorId() {
        return this.moderatorId;
    }

    /**
     * Getter for <code>public.tempban.duration</code>.
     */
    public DayToSecond getDuration() {
        return this.duration;
    }

    /**
     * Getter for <code>public.tempban.start</code>.
     */
    public Instant getStart() {
        return this.start;
    }

    /**
     * Getter for <code>public.tempban.reason</code>.
     */
    public String getReason() {
        return this.reason;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tempban (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(userId);
        sb.append(", ").append(moderatorId);
        sb.append(", ").append(duration);
        sb.append(", ").append(start);
        sb.append(", ").append(reason);

        sb.append(")");
        return sb.toString();
    }
}
