/*
 * This file is generated by jOOQ.
 */
package io.github.org.programming.jooq.tables.records;


import io.github.org.programming.jooq.tables.Tempban;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.DayToSecond;

import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempbanRecord extends UpdatableRecordImpl<TempbanRecord> implements Record7<Integer, String, String, String, DayToSecond, Instant, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tempban.id</code>.
     */
    public TempbanRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tempban.guild_id</code>.
     */
    public TempbanRecord setGuildId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tempban.user_id</code>.
     */
    public TempbanRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tempban.moderator_id</code>.
     */
    public TempbanRecord setModeratorId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.moderator_id</code>.
     */
    public String getModeratorId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tempban.duration</code>.
     */
    public TempbanRecord setDuration(DayToSecond value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.duration</code>.
     */
    public DayToSecond getDuration() {
        return (DayToSecond) get(4);
    }

    /**
     * Setter for <code>public.tempban.start</code>.
     */
    public TempbanRecord setStart(Instant value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.start</code>.
     */
    public Instant getStart() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.tempban.reason</code>.
     */
    public TempbanRecord setReason(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tempban.reason</code>.
     */
    public String getReason() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, DayToSecond, Instant, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, DayToSecond, Instant, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tempban.TEMPBAN.ID;
    }

    @Override
    public Field<String> field2() {
        return Tempban.TEMPBAN.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return Tempban.TEMPBAN.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return Tempban.TEMPBAN.MODERATOR_ID;
    }

    @Override
    public Field<DayToSecond> field5() {
        return Tempban.TEMPBAN.DURATION;
    }

    @Override
    public Field<Instant> field6() {
        return Tempban.TEMPBAN.START;
    }

    @Override
    public Field<String> field7() {
        return Tempban.TEMPBAN.REASON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getModeratorId();
    }

    @Override
    public DayToSecond component5() {
        return getDuration();
    }

    @Override
    public Instant component6() {
        return getStart();
    }

    @Override
    public String component7() {
        return getReason();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getModeratorId();
    }

    @Override
    public DayToSecond value5() {
        return getDuration();
    }

    @Override
    public Instant value6() {
        return getStart();
    }

    @Override
    public String value7() {
        return getReason();
    }

    @Override
    public TempbanRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TempbanRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public TempbanRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public TempbanRecord value4(String value) {
        setModeratorId(value);
        return this;
    }

    @Override
    public TempbanRecord value5(DayToSecond value) {
        setDuration(value);
        return this;
    }

    @Override
    public TempbanRecord value6(Instant value) {
        setStart(value);
        return this;
    }

    @Override
    public TempbanRecord value7(String value) {
        setReason(value);
        return this;
    }

    @Override
    public TempbanRecord values(Integer value1, String value2, String value3, String value4, DayToSecond value5, Instant value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TempbanRecord
     */
    public TempbanRecord() {
        super(Tempban.TEMPBAN);
    }

    /**
     * Create a detached, initialised TempbanRecord
     */
    public TempbanRecord(Integer id, String guildId, String userId, String moderatorId, DayToSecond duration, Instant start, String reason) {
        super(Tempban.TEMPBAN);

        setId(id);
        setGuildId(guildId);
        setUserId(userId);
        setModeratorId(moderatorId);
        setDuration(duration);
        setStart(start);
        setReason(reason);
    }

    /**
     * Create a detached, initialised TempbanRecord
     */
    public TempbanRecord(io.github.org.programming.jooq.tables.pojos.Tempban value) {
        super(Tempban.TEMPBAN);

        if (value != null) {
            setId(value.getId());
            setGuildId(value.getGuildId());
            setUserId(value.getUserId());
            setModeratorId(value.getModeratorId());
            setDuration(value.getDuration());
            setStart(value.getStart());
            setReason(value.getReason());
        }
    }
}
