/*
 * This file is generated by jOOQ.
 */
package io.github.org.programming.jooq;


import io.github.org.programming.jooq.tables.Activequestionmessage;
import io.github.org.programming.jooq.tables.Askthread;
import io.github.org.programming.jooq.tables.Moderation;
import io.github.org.programming.jooq.tables.Tempban;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.activequestionmessage</code>.
     */
    public final Activequestionmessage ACTIVEQUESTIONMESSAGE = Activequestionmessage.ACTIVEQUESTIONMESSAGE;

    /**
     * The table <code>public.askthread</code>.
     */
    public final Askthread ASKTHREAD = Askthread.ASKTHREAD;

    /**
     * The table <code>public.moderation</code>.
     */
    public final Moderation MODERATION = Moderation.MODERATION;

    /**
     * The table <code>public.tempban</code>.
     */
    public final Tempban TEMPBAN = Tempban.TEMPBAN;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Activequestionmessage.ACTIVEQUESTIONMESSAGE,
            Askthread.ASKTHREAD,
            Moderation.MODERATION,
            Tempban.TEMPBAN
        );
    }
}
