/*
 * This file is generated by jOOQ.
 */
package io.github.org.programming.jooq;


import io.github.org.programming.jooq.tables.Activequestionmessage;
import io.github.org.programming.jooq.tables.Askthread;
import io.github.org.programming.jooq.tables.Moderation;
import io.github.org.programming.jooq.tables.Tempban;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.activequestionmessage</code>.
     */
    public static final Activequestionmessage ACTIVEQUESTIONMESSAGE = Activequestionmessage.ACTIVEQUESTIONMESSAGE;

    /**
     * The table <code>public.askthread</code>.
     */
    public static final Askthread ASKTHREAD = Askthread.ASKTHREAD;

    /**
     * The table <code>public.moderation</code>.
     */
    public static final Moderation MODERATION = Moderation.MODERATION;

    /**
     * The table <code>public.tempban</code>.
     */
    public static final Tempban TEMPBAN = Tempban.TEMPBAN;
}
