name: Basic checks

on: [pull_request]

env:
  JAVA_VERSION: 17
  DISTRIBUTION: adopt

jobs:
  spotless:
    name: "Spotless"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check
        run: ./gradlew spotlessCheck

  gradle-test:
    name: "Gradle Test"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check
        run: ./gradlew test

      coverage:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - name: Setup java
            uses: actions/setup-java@v2
            with:
              distribution: "temurin"
              java-version: "17"
          - name: Build project
            uses: gradle/gradle-build-action@v2
            with:
              arguments: test jacocoTestReport
          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v3
          - name: Upload test report
            uses: actions/upload-artifact@v3
            with:
              path: build/reports/tests/test/
              name: Test Report
              retention-days: 14
          - name: Upload coverage report
            uses: actions/upload-artifact@v3
            with:
              path: build/reports/jacoco/test/
              name: Coverage Report
              retention-days: 14