name: Basic checks

on: [pull_request]

jobs:
  codecov:
    name: "codecov"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3